{"name": "Проверка неуспешной авторизации с неверным логином", "status": "passed", "description": "Проверяем статус 404 и текст ошибки \"Учетная запись не найдена\" в теле ответа", "start": 1727511363581, "stop": 1727511363969, "uuid": "c98f70eb-2b72-4537-8ee9-65eebe6a154a", "historyId": "76490535d990169e7ebe9d3d1278ae7e", "testCaseId": "76490535d990169e7ebe9d3d1278ae7e", "fullName": "tests.test_login_courier.TestLoginCourier#test_wrong_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-4NMD288"}, {"name": "thread", "value": "16484-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}